[settings]
experimental = true
lockfile = true

[tools]
python = "3.14"
pre-commit = "4.5.1"
act = "0.2.87"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks."setup:dev"]
run = "python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt"

[hooks.postinstall]
script = """
#!/usr/bin/env bash
pre-commit install --install-hooks
mise run setup:dev
"""
